# Generated by Django 5.2 on 2025-04-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mr', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receives_govt_benefits', models.BooleanField(default=False)),
                ('recent_short_term_loans', models.BooleanField(default=False)),
                ('consent_lead_gen', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('want_offers', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_status', models.CharField(max_length=100)),
                ('residency_status', models.CharField(max_length=100)),
                ('unit_number', models.CharField(blank=True, max_length=10)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('street_type', models.CharField(max_length=50)),
                ('alley', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=100)),
                ('employment_years', models.IntegerField()),
                ('employment_months', models.IntegerField()),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_frequency', models.CharField(max_length=50)),
                ('next_pay_day', models.DateField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='not approved', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.customer')),
            ],
        ),
    ]
