# Generated by Django 5.2 on 2025-04-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('supported_loan_types', models.CharField(help_text='Comma-separated values', max_length=255)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_preferences', models.TextField(help_text='E.g. Accept Centrelink, Full-time only')),
                ('credit_profile_preferences', models.TextField(help_text='E.g. No defaults, Credit score above 600')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
