# Generated by Django 5.2 on 2025-04-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='applicant_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='alley',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='consent_lead_gen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_frequency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='net_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='next_pay_day',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='receives_govt_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recent_short_term_loans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='referral_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='residency_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='residential_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='street_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='street_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='suburb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='title',
            field=models.CharField(default='Mr', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='want_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_purpose',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='not approved', max_length=50),
        ),
    ]
