version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loanpilot
      POSTGRES_USER: garry
      POSTGRES_PASSWORD: garry
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: gunicorn loanpilot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
