services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loanpilot
      POSTGRES_USER: garry
      POSTGRES_PASSWORD: garry
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DATABASE_NAME=loanpilot
      - DATABASE_USER=garry
      - DATABASE_PASSWORD=garry
      - DATABASE_HOST=postgres  # this MUST match your DB service name
      - DATABASE_PORT=5432
    command: gunicorn loanpilot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend                 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
